/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ElectricityBillCounter;

/**
 *
 * @author User
 */
public class Calculation extends javax.swing.JFrame {

    /**
     * Creates new form Calculation
     */
    public Calculation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //comments
    //comments
    //comments
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblBillNo = new javax.swing.JLabel();
        txtBillNo = new javax.swing.JTextField();
        lblCustomerName = new javax.swing.JLabel();
        txtCustomerName = new javax.swing.JTextField();
        lblWorkingHours = new javax.swing.JLabel();
        lblPower = new javax.swing.JLabel();
        lblNumber = new javax.swing.JLabel();
        btUnit = new javax.swing.JButton();
        lblLight = new javax.swing.JLabel();
        lblFan = new javax.swing.JLabel();
        lblTV = new javax.swing.JLabel();
        lblFridge = new javax.swing.JLabel();
        txtFanPower = new javax.swing.JTextField();
        txtLightNumber = new javax.swing.JTextField();
        txtTVWorkingHours = new javax.swing.JTextField();
        txtLightPower = new javax.swing.JTextField();
        txtFridgePower = new javax.swing.JTextField();
        txtTVPower = new javax.swing.JTextField();
        txtTotalUnit = new javax.swing.JTextField();
        txtFanWorkingHours = new javax.swing.JTextField();
        txtLightWorkingHours = new javax.swing.JTextField();
        txtFridgeWorkingHours = new javax.swing.JTextField();
        txtFridgeNumber = new javax.swing.JTextField();
        txtFanNumber = new javax.swing.JTextField();
        txtTVNumber = new javax.swing.JTextField();
        txtFanUnit = new javax.swing.JTextField();
        txtLightUnit = new javax.swing.JTextField();
        txtFridgeUnit = new javax.swing.JTextField();
        btTotalUnit = new javax.swing.JButton();
        txtTVUnit = new javax.swing.JTextField();
        lblPerUnitPrice = new javax.swing.JLabel();
        txtPerUnitPrice = new javax.swing.JTextField();
        lblAdvancedPayment = new javax.swing.JLabel();
        txtPreviousMonthBill = new javax.swing.JTextField();
        lblPreviousMonthBill = new javax.swing.JLabel();
        txtAdvancedPayment = new javax.swing.JTextField();
        lblQ = new javax.swing.JLabel();
        btFinalBill = new javax.swing.JButton();
        txtYorN = new javax.swing.JTextField();
        lblYorN = new javax.swing.JLabel();
        txtFinalBill = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btBill = new javax.swing.JButton();
        txtBill = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtShow = new javax.swing.JTextArea();
        btShow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\University\\Spring2021\\SE211\\SE211.Project\\Electricity pic.jpg")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("Electricity Bill Counter");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblBillNo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblBillNo.setText("Bill No");

        txtBillNo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblCustomerName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblCustomerName.setText("Customer Name");

        txtCustomerName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblWorkingHours.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblWorkingHours.setText("Working Hours");

        lblPower.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPower.setText("Power(Watt)");

        lblNumber.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblNumber.setText("Number");

        btUnit.setBackground(new java.awt.Color(0, 0, 255));
        btUnit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btUnit.setText("Unit");
        btUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUnitActionPerformed(evt);
            }
        });

        lblLight.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblLight.setText("Light");

        lblFan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblFan.setText("Fan");

        lblTV.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblTV.setText("TV");

        lblFridge.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblFridge.setText("Fridge");

        txtFanPower.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtLightNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtTVWorkingHours.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtTVWorkingHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTVWorkingHoursActionPerformed(evt);
            }
        });

        txtLightPower.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtFridgePower.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtTVPower.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtTotalUnit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtFanWorkingHours.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtFanWorkingHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFanWorkingHoursActionPerformed(evt);
            }
        });

        txtLightWorkingHours.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtLightWorkingHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLightWorkingHoursActionPerformed(evt);
            }
        });

        txtFridgeWorkingHours.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtFridgeWorkingHours.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFridgeWorkingHoursActionPerformed(evt);
            }
        });

        txtFridgeNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtFanNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtTVNumber.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtFanUnit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtLightUnit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtFridgeUnit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        btTotalUnit.setBackground(new java.awt.Color(0, 0, 255));
        btTotalUnit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btTotalUnit.setText("Total Unit");
        btTotalUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTotalUnitActionPerformed(evt);
            }
        });

        txtTVUnit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblPerUnitPrice.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPerUnitPrice.setText("Per Unit Price");

        txtPerUnitPrice.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblAdvancedPayment.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblAdvancedPayment.setText("Advanced Payment");

        txtPreviousMonthBill.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblPreviousMonthBill.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblPreviousMonthBill.setText("Previous Month Bill");

        txtAdvancedPayment.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblQ.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblQ.setText("Are Paying Bill In Due Time ??");

        btFinalBill.setBackground(new java.awt.Color(0, 0, 255));
        btFinalBill.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btFinalBill.setText("Final Bill");
        btFinalBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalBillActionPerformed(evt);
            }
        });

        txtYorN.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblYorN.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblYorN.setText("Yes/No");

        txtFinalBill.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("tk");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("tk");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("tk");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("tk");

        btBill.setBackground(new java.awt.Color(0, 0, 255));
        btBill.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btBill.setText("Bill");
        btBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBillActionPerformed(evt);
            }
        });

        txtBill.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("tk");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFridge, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLight, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTV, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPerUnitPrice)
                                    .addComponent(btBill))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtFanPower)
                                    .addComponent(lblPower, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                    .addComponent(txtLightPower)
                                    .addComponent(txtFridgePower)
                                    .addComponent(txtTVPower))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblWorkingHours, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                            .addComponent(txtTVWorkingHours)
                                            .addComponent(txtFanWorkingHours, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtLightWorkingHours)
                                            .addComponent(txtFridgeWorkingHours))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtTVNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtTVUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(txtTotalUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtLightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtFridgeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtFanNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addGap(41, 41, 41)
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(btUnit)
                                                                .addComponent(txtFanUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(txtLightUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addComponent(txtFridgeUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(btTotalUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(109, 109, 109)))
                                .addGap(21, 21, 21))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPreviousMonthBill, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAdvancedPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtPerUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtAdvancedPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtBill, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtPreviousMonthBill, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(lblYorN, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(24, 24, 24)
                                                .addComponent(txtYorN, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btFinalBill)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtFinalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(lblQ, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(37, 37, 37))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBillNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWorkingHours, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPower, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btUnit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFanPower, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFanWorkingHours, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFanNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFanUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLight, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtLightPower, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLightWorkingHours, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtLightUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFridge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFridgePower, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFridgeWorkingHours, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFridgeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTVPower, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTVWorkingHours, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTVNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTVUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtFridgeUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btTotalUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTotalUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(lblQ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPerUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPerUnitPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btBill, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBill, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtYorN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblYorN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPreviousMonthBill, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPreviousMonthBill, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btFinalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFinalBill, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdvancedPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAdvancedPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
        );

        txtShow.setColumns(20);
        txtShow.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtShow.setRows(5);
        jScrollPane1.setViewportView(txtShow);

        btShow.setBackground(new java.awt.Color(0, 0, 255));
        btShow.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btShow.setText("Show");
        btShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(230, 230, 230))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btShow, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btShow, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int bNo;
    String cName;
    
    double fPower;
    double lPower;
    double frPower;
    double tvPower;
    
    double fWH;
    double lWH;
    double frWH;
    double tvWH;
    
    int fNo;
    int lNo;
    int frNo;
    int tvNo;
    
    double fUnit;
    double lUnit;
    double frUnit;
    double tvUnit;
    double totalUnit;
    
    double pup;
    double pmb;
    double ap;
    String Q;
    int delayFee;
    
    double bill;
    double finalBill;
    
    public void setValue(){
        String strbNo = txtBillNo.getText();
        bNo = Integer.parseInt(strbNo);
        cName = txtCustomerName.getText();   
    }
    
    public void setUnit(){
        String strFPower = txtFanPower.getText();
        fPower = Double.parseDouble(strFPower);
        String strLPower = txtLightPower.getText();
        lPower = Double.parseDouble(strLPower);
        String strFRPower = txtFridgePower.getText();
        frPower = Double.parseDouble(strFRPower);
        String strTVPower = txtTVPower.getText();
        tvPower = Double.parseDouble(strTVPower);
        
        String strFWH = txtFanWorkingHours.getText();
        fWH = Double.parseDouble(strFWH);
        String strLWH = txtLightWorkingHours.getText();
        lWH = Double.parseDouble(strLWH);
        String strFRWH = txtFridgeWorkingHours.getText();
        frWH = Double.parseDouble(strFRWH);
        String strTVWH = txtTVWorkingHours.getText();
        tvWH = Double.parseDouble(strTVWH);
        
        String strFNo = txtFanNumber.getText();
        fNo = Integer.parseInt(strFNo);
        String strLNo = txtLightNumber.getText();
        lNo = Integer.parseInt(strLNo);
        String strFRNo = txtFridgeNumber.getText();
        frNo = Integer.parseInt(strFRNo);
        String strTVNo = txtTVNumber.getText();
        tvNo = Integer.parseInt(strTVNo);
        
    }
   
    public void unitCalculation(){
        setUnit();
        fUnit = (fPower*fWH*fNo)/1000;
        lUnit = (lPower*lWH*lNo)/1000;
        frUnit = (frPower*frWH*frNo)/1000;
        tvUnit = (tvPower*tvWH*tvNo)/1000;  
        totalUnit = fUnit+lUnit+frUnit+tvUnit;
    }
    
    public void billCalculation(){
        unitCalculation();
        String strPUP = txtPerUnitPrice.getText();
        pup = Double.parseDouble(strPUP);
        bill = (double)totalUnit*pup;
    }
    public void finalBillCalculation(){
        billCalculation();
        String strPMB = txtPreviousMonthBill.getText();
        pmb = Double.parseDouble(strPMB);
        String strAP = txtAdvancedPayment.getText();
        ap = Double.parseDouble(strAP);
        Q = txtYorN.getText();
        if(Q.equalsIgnoreCase("no")){
            delayFee = 500;
        }
        else{
            delayFee = 0;
        }
        finalBill = (bill+pmb+delayFee)-ap;
    }
    
    private void txtTVWorkingHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTVWorkingHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTVWorkingHoursActionPerformed

    private void txtFanWorkingHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFanWorkingHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFanWorkingHoursActionPerformed

    private void txtLightWorkingHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLightWorkingHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLightWorkingHoursActionPerformed

    private void txtFridgeWorkingHoursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFridgeWorkingHoursActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFridgeWorkingHoursActionPerformed

    private void btFinalBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalBillActionPerformed
        finalBillCalculation();
        txtFinalBill.setText(String.valueOf(finalBill));
    }//GEN-LAST:event_btFinalBillActionPerformed

    
    private void btUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUnitActionPerformed
        unitCalculation();
        txtFanUnit.setText(String.valueOf(fUnit));
        txtLightUnit.setText(String.valueOf(lUnit));
        txtFridgeUnit.setText(String.valueOf(frUnit));
        txtTVUnit.setText(String.valueOf(tvUnit));
    }//GEN-LAST:event_btUnitActionPerformed

    private void btTotalUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTotalUnitActionPerformed
        unitCalculation();
        txtTotalUnit.setText(String.valueOf(totalUnit ));
    }//GEN-LAST:event_btTotalUnitActionPerformed

    private void btBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBillActionPerformed
        billCalculation();
        txtBill.setText(String.valueOf(bill ));
    }//GEN-LAST:event_btBillActionPerformed

    private void btShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btShowActionPerformed
        setValue();
        unitCalculation();
        finalBillCalculation();
        txtShow.setText("\n\nBill No : "+String.valueOf(bNo )+"\n\nCustomer Name : "+String.valueOf(cName )+"\n\nTotal Unit : "+String.valueOf(totalUnit )+"\n\nDelay Fee : "+String.valueOf(delayFee )+ " tk"+"\n\nFinal Bill : "+String.valueOf(finalBill )+" tk");
    }//GEN-LAST:event_btShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBill;
    private javax.swing.JButton btFinalBill;
    private javax.swing.JButton btShow;
    private javax.swing.JButton btTotalUnit;
    private javax.swing.JButton btUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAdvancedPayment;
    private javax.swing.JLabel lblBillNo;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblFan;
    private javax.swing.JLabel lblFridge;
    private javax.swing.JLabel lblLight;
    private javax.swing.JLabel lblNumber;
    private javax.swing.JLabel lblPerUnitPrice;
    private javax.swing.JLabel lblPower;
    private javax.swing.JLabel lblPreviousMonthBill;
    private javax.swing.JLabel lblQ;
    private javax.swing.JLabel lblTV;
    private javax.swing.JLabel lblWorkingHours;
    private javax.swing.JLabel lblYorN;
    private javax.swing.JTextField txtAdvancedPayment;
    private javax.swing.JTextField txtBill;
    private javax.swing.JTextField txtBillNo;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtFanNumber;
    private javax.swing.JTextField txtFanPower;
    private javax.swing.JTextField txtFanUnit;
    private javax.swing.JTextField txtFanWorkingHours;
    private javax.swing.JTextField txtFinalBill;
    private javax.swing.JTextField txtFridgeNumber;
    private javax.swing.JTextField txtFridgePower;
    private javax.swing.JTextField txtFridgeUnit;
    private javax.swing.JTextField txtFridgeWorkingHours;
    private javax.swing.JTextField txtLightNumber;
    private javax.swing.JTextField txtLightPower;
    private javax.swing.JTextField txtLightUnit;
    private javax.swing.JTextField txtLightWorkingHours;
    private javax.swing.JTextField txtPerUnitPrice;
    private javax.swing.JTextField txtPreviousMonthBill;
    private javax.swing.JTextArea txtShow;
    private javax.swing.JTextField txtTVNumber;
    private javax.swing.JTextField txtTVPower;
    private javax.swing.JTextField txtTVUnit;
    private javax.swing.JTextField txtTVWorkingHours;
    private javax.swing.JTextField txtTotalUnit;
    private javax.swing.JTextField txtYorN;
    // End of variables declaration//GEN-END:variables
}
